namespace RogueEngine.Core.Models;

/// <summary>
/// A named place in the game world that has its own <see cref="AsciiMap"/>,
/// a set of resident <see cref="Entity"/> objects, and arbitrary persistent
/// key-value state.  Locations are nodes in an <see cref="Overworld"/> graph.
/// </summary>
public sealed class OverworldLocation
{
    /// <summary>Unique identifier for this location.</summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>Human-readable name (e.g. "Goblin Cave", "Town Square").</summary>
    public string Name { get; set; } = "Unnamed Location";

    /// <summary>Optional flavour description shown on arrival.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Column position on the overworld map used for display and distance
    /// calculations.  Units are arbitrary tiles.
    /// </summary>
    public int WorldX { get; set; }

    /// <summary>Row position on the overworld map.</summary>
    public int WorldY { get; set; }

    /// <summary>
    /// The ASCII map that represents the interior of this location.
    /// <see langword="null"/> until the location is first visited or explicitly
    /// generated by a <see cref="NodeType.GenerateLocation"/> node.
    /// </summary>
    public AsciiMap? Map { get; set; }

    /// <summary>
    /// Entities that currently reside in this location.
    /// Their positions are relative to <see cref="Map"/>.
    /// </summary>
    public List<Entity> Entities { get; } = [];

    /// <summary>
    /// Named exits from this location.
    /// Keys are direction / exit names (e.g. "North", "Enter Cave");
    /// values are the <see cref="OverworldLocation.Id"/> of the destination.
    /// </summary>
    public Dictionary<string, Guid> Exits { get; } = [];

    /// <summary>
    /// Arbitrary persistent key-value data for this location
    /// (e.g. quest flags, loot state, enemy counts).
    /// </summary>
    public Dictionary<string, string> PersistentData { get; } = [];

    /// <summary>Whether this location has been visited at least once.</summary>
    public bool HasBeenVisited { get; set; }

    /// <summary>
    /// Adds a named exit from this location to another.
    /// </summary>
    /// <param name="exitName">Direction or descriptive label (e.g. "North").</param>
    /// <param name="destinationId">The destination location's <see cref="Id"/>.</param>
    public void AddExit(string exitName, Guid destinationId) =>
        Exits[exitName] = destinationId;

    /// <inheritdoc/>
    public override string ToString() => $"[Location] {Name} @ ({WorldX},{WorldY})";
}
